### ISSUE TITLE
pretrained_model_liteflownet = (sintel.pth)

### ISSUE THREAD

**Issue by guiweit** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#1]
Hello, thanks for sharing this implementation.
Can you also share your pretrained model of liteflownet? My email address is guiweit@icloud.com. Thank you!

**Comment by lukas-blecher** [comment]
They are linked in the README: 
> Weights for LiteFlowNet are hosted by [sniklaus](https://github.com/sniklaus): [default](http://content.sniklaus.com/github/pytorch-liteflownet/network-default.pytorch), [kitti](http://content.sniklaus.com/github/pytorch-liteflownet/network-kitti.pytorch), [sintel](http://content.sniklaus.com/github/pytorch-liteflownet/network-sintel.pytorch).

**Comment by guiweit** [comment]
Thanks very much!
