### ISSUE TITLE
No pretrained liteflow model

### ISSUE THREAD

**Issue by Hiddennn** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#3]
When running python tools/video_inpaint.py --frame_dir ./demo/frames --MASK_ROOT ./demo/masks --img_size 512 832 --LiteFlowNet --DFC --ResNet101 --Propagation,it showed:
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/sintel.pth'

It seems that i dont have the sintel.pth file.Could you help me?thx.

**Comment by lukas-blecher** [comment]
They are linked in the README:

> Weights for LiteFlowNet are hosted by [sniklaus](https://github.com/sniklaus): [default](http://content.sniklaus.com/github/pytorch-liteflownet/network-default.pytorch), [kitti](http://content.sniklaus.com/github/pytorch-liteflownet/network-kitti.pytorch), [sintel](http://content.sniklaus.com/github/pytorch-liteflownet/network-sintel.pytorch).

Download one of them. You can parse it by adding `--pretrained_model_liteflownet path_to_weights`

**Comment by Hiddennn** [comment]
Thank you very much, it works

**Comment by mayingwuhu** [comment]
The three links-sniklaus: default, kitti, sintel.is not work.Could you tell me how to handle this question?thx!

**Comment by lukas-blecher** [comment]
They work fine for me. Here they are in raw format
- http://content.sniklaus.com/github/pytorch-liteflownet/network-default.pytorch
- http://content.sniklaus.com/github/pytorch-liteflownet/network-kitti.pytorch
- http://content.sniklaus.com/github/pytorch-liteflownet/network-sintel.pytorch

**Comment by mayingwuhu** [comment]
Thank you very much! I can download them now!
