### ISSUE TITLE
Lack of './pretrained_models/sintel.pth'

### ISSUE THREAD

**Issue by LK-Peng** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#4]
Hi, all
When I tried to execute example, I encountered with this issues.
Could you please share this file with me?

![5$2@9I4RUB11L4F)%~PDEHQ](https://user-images.githubusercontent.com/54395730/89280279-fa2f9d00-d67a-11ea-8f22-224455ae1779.png)

**Comment by lukas-blecher** [comment]
Hi,
please see Issue #3 (https://github.com/lukas-blecher/Deep-Flow-Guided-Video-Inpainting/issues/3#issuecomment-636317366)

The weights are linked in the README
