### ISSUE TITLE
Package Version

### ISSUE THREAD

**Issue by LK-Peng** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#5]
Hi,
When I tried to execute example, I encountered with this issues.
I think it's a problem with the torch and sensorboardX version. Do you have the same problem?

![N}IH`1NA%3 QLV_()Q1AI](https://user-images.githubusercontent.com/54395730/89289759-5a7a0b00-d68a-11ea-8170-dc13d5aabdb3.png)

**Comment by lukas-blecher** [comment]
It runs for me locally.
What pytorch version are you using?

**Comment by LK-Peng** [comment]
> It runs for me locally.
> What pytorch version are you using?

0.4.1
I have tried 0.4.0. It can't work, too.
![QQ图片20200804201711](https://user-images.githubusercontent.com/54395730/89292810-851a9280-d68f-11ea-9d84-f9f8a7c10b9c.png)

**Comment by lukas-blecher** [comment]
This repository needs at least version 1.3.0 I believe.
At least that's what the liteflownet implementation references in the [requirements](https://github.com/sniklaus/pytorch-liteflownet/blob/320a634ec4ffe15532e04dd50c07094719ec2a92/requirements.txt#L4)

**Comment by lukas-blecher** [comment]
I did not update the dockerfile. Did you install using the docker?

**Comment by LK-Peng** [comment]
Ok. Thank you. I will try 1.3.0.

I did't use the docker.  I use anaconda for management. Is docker more convenient?

**Comment by LK-Peng** [comment]
> This repository needs at least version 1.3.0 I believe.
> At least that's what the liteflownet implementation references in the [requirements](https://github.com/sniklaus/pytorch-liteflownet/blob/320a634ec4ffe15532e04dd50c07094719ec2a92/requirements.txt#L4)

It works! Thank you

**Comment by lukas-blecher** [comment]
You're welcome
