### ISSUE TITLE
unexpected keyword argument 'align_corners'

### ISSUE THREAD

**Issue by balablb** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#6]
pretrain_model download from  _Weights for LiteFlowNet are hosted by sniklaus: default, kitti, sintel._
like **network-default.pytorch**  is different from **'./pretrained_models/default.pth'**

The following is the error message:

====> Loading /home/xieyl/Deep-Flow-Guided-Video-Inpainting/pretrained_models/network-default.pytorch
  0%|                                                                                                                                        | 0/158 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/infer_liteflownet.py", line 150, in <module>
    main()
  File "tools/infer_liteflownet.py", line 146, in main
    infer(args)
  File "tools/infer_liteflownet.py", line 81, in infer
    flow = estimate(Flownet, f1, f2)
  File "tools/infer_liteflownet.py", line 51, in estimate
    tensorFlow = torch.nn.functional.interpolate(input=model(tensorPreprocessedFirst, tensorPreprocessedSecond), size=(intHeight, intWidth), mode='bilinear', align_corners=False)
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xieyl/Deep-Flow-Guided-Video-Inpainting/models/LiteFlowNet_Models/LiteFlowNet.py", line 296, in forward
    tensorFlow = self.moduleSubpixel[intLevel](tensorFirst[intLevel], tensorSecond[intLevel], tensorFeaturesFirst[intLevel], tensorFeaturesSecond[intLevel], tensorFlow)
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xieyl/Deep-Flow-Guided-Video-Inpainting/models/LiteFlowNet_Models/LiteFlowNet.py", line 190, in forward
    tensorFeaturesSecond = Backward(tensorInput=tensorFeaturesSecond, tensorFlow=tensorFlow * self.dblBackward)
  File "/home/xieyl/Deep-Flow-Guided-Video-Inpainting/models/LiteFlowNet_Models/LiteFlowNet.py", line 25, in Backward
    return torch.nn.functional.grid_sample(input=tensorInput, grid=(Backward_tensorGrid[str(tensorFlow.size())] + tensorFlow).permute(0, 2, 3, 1), mode='bilinear', padding_mode='zeros', align_corners=True)
TypeError: grid_sample() got an unexpected keyword argument 'align_corners'

**Comment by lukas-blecher** [comment]
you need `torch>=1.3.0`.
what version of pytorch do you have installed?

**Comment by balablb** [comment]
> you need `torch>=1.3.0`.
> what version of pytorch do you have installed?

Sorry for my late answer , my version is:
torch                     1.3.0                    pypi_0    pypi
torchvision               0.4.1                    pypi_0    pypi

**Comment by lukas-blecher** [comment]
The keyword argument `align_corners` was introduced in 1.3.0: https://pytorch.org/docs/1.3.0/nn.functional.html#grid-sample

I don't understand why it is throwing this error if you have the correct version installed.
What does the "pypi_0 pypi" mean?

Are you sure it is using this particular pytorch installation? 
If nothing else helps you can just remove the keyword argument. The behavior should be the same.

> The old functionality can still be achieved by setting `align_corners=True`, but the default is now set to `align_corners=False`

**Comment by balablb** [comment]
Thanks for your reply，I remove _align_corners=True_，the program can run normally ~  "pypi_0 pypi" means install from pip
