### ISSUE TITLE
train DeepFill v1 model

### ISSUE THREAD

**Issue by balablb** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#8]
I want to train my  DeepFill v1 model with my dataset.Can you tell me how to do it

**Comment by lukas-blecher** [comment]
I do not have the training scripts.
The authors of DeepFill released their training code (e.g v1:https://github.com/JiahuiYu/generative_inpainting/tree/v1.0.0)
There are also other implementations on github if you are looking for PyTorch code instead.

**Comment by balablb** [comment]
> I do not have the training scripts.
> The authors of DeepFill released their training code (e.g v1:https://github.com/JiahuiYu/generative_inpainting/tree/v1.0.0)
> There are also other implementations on github if you are looking for PyTorch code instead.

Thanks~
