### ISSUE TITLE
Something wrong with results of video inpainting demo.

### ISSUE THREAD

**Issue by JOyer193** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#9]
I used the following command to test.
python tools/video_inpaint.py --frame_dir ./demo/frames --MASK_ROOT ./demo/masks --img_size 512 832 --LiteFlowNet --DFC --ResNet101 --Propagation

Results turn out to be really bad. Even running deepfill1 independently provides better results than video inpainting.
 
![00000](https://user-images.githubusercontent.com/23361879/106863580-aeca7a00-6703-11eb-94f2-ee65972ac242.png)
![00004](https://user-images.githubusercontent.com/23361879/106863676-d02b6600-6703-11eb-8442-ca23577d50dc.png)

**Comment by lukas-blecher** [comment]
Hi,
- How many frames are in the `frames` and `masks` directories? The more the better is the result.
- What PyTorch version are you using?
- How many propagation iterations does it need to until the process stops?

It has to be one of these because the comand 
`python tools/video_inpaint.py --frame_dir ./demo/frames --MASK_ROOT ./demo/masks --img_size 512 832 --LiteFlowNet --DFC --ResNet101 --Propagation`
still works fine for me.

**Comment by JOyer193** [comment]
> Hi,
> 
> * How many frames are in the `frames` and `masks` directories? The more the better is the result.
> * What PyTorch version are you using?
> * How many propagation iterations does it need to until the process stops?
> 
> It has to be one of these because the comand
> `python tools/video_inpaint.py --frame_dir ./demo/frames --MASK_ROOT ./demo/masks --img_size 512 832 --LiteFlowNet --DFC --ResNet101 --Propagation`
> still works fine for me.

Thanks for your fast reply.

- I used all 80 frames and mask from those directories.
- Pytorch 1.3 and cupy-cuda100
- It seems only 80 frames have been processed within 2 iterations.

**Comment by lukas-blecher** [comment]
I'm guessing you are using the standard models: sintel, resnet101_movie and imagenet_deepfill?
That's very weird. It should produce the same results I get.
When I run it, it also only takes one propagation iteration to stop.
Did you change any other default settings in the code?

**Comment by JOyer193** [comment]
> I'm guessing you are using the standard models: sintel, resnet101_movie and imagenet_deepfill?
> That's very weird. It should produce the same results I get.
> When I run it, it also only takes one propagation iteration to stop.
> Did you change any other default settings in the code?

It seems like my environment causes the problem. I used exactly the same code in a new environment, It works alright.
